import express from "express";
import autorController from "../controllers/autorController.js";
import { verifyToken } from "../middlewares/auth/tokenMiddleware.js";
const router = express.Router();
router.get("/", verifyToken, autorController.obtenerAutores);
router.get("/:id", verifyToken, autorController.obtenerAutorPorId);
router.post("/", verifyToken, autorController.crearAutor);
router.put("/:id", verifyToken, autorController.actualizarAutor);
router.delete("/:id", verifyToken, autorController.eliminarAutor);
export default router;