import express from "express";
import CategoriasController from "../controllers/categoriaController.js";
import { verifyToken } from "../middlewares/auth/index.js";
const router = express.Router();
router.get("/", verifyToken, CategoriasController.getAllCategorias);
router.get("/:id", verifyToken, CategoriasController.getCategoriaById);
router.post("/", verifyToken, CategoriasController.createCategoria);
router.put("/:id", verifyToken, CategoriasController.updateCategoria);
router.delete("/:id", verifyToken, CategoriasController.deleteCategoria);
export default router;